from pyspark.sql import SparkSession


#  Using this function as spark instance
def spark_inst():
    return SparkSession.builder.master("local[*]") \
        .appName('Spark') \
        .getOrCreate()


COL_2019 = {
    "session": "Session",
    "contrat_etab": "Contrat établissement",
    "cod_uai": "cod_uai",
    "g_ea_lib_vx": "g_ea_lib_vx",
    "dep": "dep",
    "dep_lib": "dep_lib",
    "region_etab_aff": "region_etab_aff",
    "acad_mies": "acad_mies",
    "fili": "Filière",
    "form_lib_voe_acc": "form_lib_voe_acc",
    "regr_forma": "regr_forma",
    "fil_lib_voe_acc": "fil_lib_voe_acc",
    "detail_forma": "detail_forma",
    "lien_form_psup": "lien_form_psup",
    "g_olocalisation_des_formations": "g_olocalisation_des_formations",
    "capa_fin": "capa_fin",
    "voe_tot": "voe_tot",
    "voe_tot_f": "voe_tot_f",
    "nb_voe_pp": "nb_voe_pp",
    "nb_voe_pp_internat": "nb_voe_pp_internat",
    "nb_voe_pp_bg": "nb_voe_pp_bg",
    "nb_voe_pp_bg_brs": "nb_voe_pp_bg_brs",
    "nb_voe_pp_bt": "nb_voe_pp_bt",
    "nb_voe_pp_bt_brs": "nb_voe_pp_bt_brs",
    "nb_voe_pp_bp": "nb_voe_pp_bp",
    "nb_voe_pp_bp_brs": "nb_voe_pp_bp_brs",
    "nb_voe_pp_at": "nb_voe_pp_at",
    "nb_voe_pc": "nb_voe_pc",
    "nb_voe_pc_bg": "nb_voe_pc_bg",
    "nb_voe_pc_bt": "nb_voe_pc_bt",
    "nb_voe_pc_bp": "nb_voe_pc_bp",
    "nb_voe_pc_at": "nb_voe_pc_at",
    "nb_cla_pp": "nb_cla_pp",
    "nb_cla_pc": "nb_cla_pc",
    "nb_cla_pp_internat": "nb_cla_pp_internat",
    "nb_cla_pp_pasinternat": "nb_cla_pp_pasinternat",
    "nb_cla_pp_bg": "nb_cla_pp_bg",
    "nb_cla_pp_bg_brs": "nb_cla_pp_bg_brs",
    "nb_cla_pp_bt": "nb_cla_pp_bt",
    "nb_cla_pp_bt_brs": "nb_cla_pp_bt_brs",
    "nb_cla_pp_bp": "nb_cla_pp_bp",
    "nb_cla_pp_bp_brs": "nb_cla_pp_bp_brs",
    "nb_cla_pp_at": "nb_cla_pp_at",
    "prop_tot": "prop_tot",
    "rang_der_max": "rang_der_max",
    "acc_tot": "acc_tot",
    "acc_tot_f": "acc_tot_f",
    "acc_pp": "acc_pp",
    "acc_pc": "acc_pc",
    "acc_debutpp": "acc_debutpp",
    "acc_datebac": "acc_datebac",
    "acc_finpp": "acc_finpp",
    "acc_internat": "acc_internat",
    "acc_brs": "acc_brs",
    "acc_neobac": "acc_neobac",
    "acc_bg": "acc_bg",
    "acc_bt": "acc_bt",
    "acc_bp": "acc_bp",
    "acc_at": "acc_at",
    "acc_mention_nonrenseignee": "acc_mention_nonrenseignee",
    "acc_sansmention": "acc_sansmention",
    "acc_ab": "acc_ab",
    "acc_tb": "acc_tb",
    "acc_bg_mention": "acc_bg_mention",
    "acc_bt_mention": "acc_bt_mention",
    "acc_bp_mention": "acc_bp_mention",
    "acc_term": "acc_term",
    "acc_term_f": "acc_term_f",
    "acc_aca_orig": "acc_aca_orig",
    "acc_aca_orig_idf": "acc_aca_orig_idf",
    "pct_acc_debutpp": "pct_acc_debutpp",
    "pct_acc_datebac": "pct_acc_datebac",
    "pct_acc_finpp": "pct_acc_finpp",
    "pct_f": "pct_f",
    "pct_aca_orig": "pct_aca_orig",
    "pct_aca_orig_idf": "pct_aca_orig_idf",
    "pct_etab_orig": "pct_etab_orig",
    "pct_bours": "pct_bours",
    "pct_neobac": "pct_neobac",
    "pct_mention_nonrenseignee": "pct_mention_nonrenseignee",
    "pct_sansmention": "pct_sansmention",
    "pct_ab": "pct_ab",
    "pct_b": "pct_b",
    "pct_tb": "pct_tb",
    "pct_bg": "pct_bg",
    "pct_bg_mention": "pct_bg_mention",
    "pct_bt": "pct_bt",
    "pct_bt_mention": "pct_bt_mention",
    "pct_bp": "pct_bp",
    "pct_bp_mention": "pct_bp_mention",
    "tri": "tri"
}

SPEC_COLS = ['session', 'contrat_etab', 'g_ea_lib_vx', 'numero_departement', 'nombre_de_boursiers']
