1. 
SELECT IDP, NOM 
FROM PROF 
WHERE ANNEE_NAISSANCE = 1972; 

2. 
SELECT * 
FROM DEVOIR 
WHERE NIVEAU = '4eme'

3. 
SELECT NOM 
FROM ETABLISSEMENT
WHERE RNE REGEXP '034.*'

4. 
SELECT IDEX, NIVEAU, PROPRIETAIRE
FROM EXERCICE 
WHERE CONTENU REGEXP '.*calculer.*'

5. 
SELECT * 
FROM EXERCICE 
WHERE NIVEAU = '3eme' OR NIVEAU = '4eme' OR NIVEAU = '5eme'
ORDER BY DATE_CREATION DESC

6. 
SELECT e.IDEX, BAREME 
FROM EXERCICE e 
JOIN CONTENU c ON e.IDEX = c.IDEX
JOIN DEVOIR d ON c.IDD = d.IDD
ORDER BY c.BAREME desc

7. 
SELECT IDEX, DATE_CREATION
FROM EXERCICE 
WHERE DATE_CREATION REGEXP'../01/2019'
ORDER BY DATE_CREATION ASC

8. 
SELECT NOTE 
FROM PASSAGE p 
JOIN ELEVE e ON p.IDEL = e.IDEL
WHERE e.IDEL = 4 AND IDD = 6


9. 
SELECT NOTE, nom, prenom
FROM PASSAGE p 
JOIN ELEVE e ON p.IDEL = e.IDEL
WHERE e.NOM = 'Dupont' AND e.PRENOM = 'Maxime' AND IDD = 7

10. 
SELECT p.NOM 
FROM PROF p 
JOIN ETABLISSEMENT e ON p.RNE = e.RNE
WHERE p.VILLE = e.LOCALITE

11. 
SELECT DISTINCT NOM, PRENOM 
FROM ELEVE e 
JOIN PASSAGE p ON e.IDEL = p.IDEL

12. 
SELECT DISTINCT RNE, e.NOM 
FROM ETABLISSEMENT e 
JOIN ELEVE el ON e.RNE = el.COLLEGE
JOIN PASSAGE p ON el.IDEL = p.IDEL

13. 
SELECT DISTINCT e.NOM, e.PRENOM
FROM ELEVE e 
JOIN PASSAGE p ON e.IDEL = p.IDEL
JOIN DEVOIR d ON p.IDD = d.IDD
WHERE e.NIVEAU != d.NIVEAU

14. 
SELECT DISTINCT e.NOM, e.PRENOM
FROM ELEVE e 
JOIN PASSAGE p ON e.IDEL = p.IDEL
JOIN CONTENU c ON p.IDD = c.IDD
WHERE c.BAREME >= 6

15. 
SELECT COUNT(*) 
FROM ELEVE

16. 
SELECT SUM(bareme) 
FROM CONTENU 
WHERE IDD = 4

17. 
SELECT COUNT(*)
FROM PROF 
WHERE IDP NOT IN (
    SELECT proprietaire
    FROM EXERCICE)

SELECT COUNT(*)
FROM PROF  p 
WHERE NOT EXISTS (
    SELECT proprietaire
    FROM EXERCICE e 
    WHERE e.PROPRIETAIRE = p.IDP
)
